name:                exercism-haskell
version:             0.1.0.0
github:              "fersilva16/exercism-haskell"
license:             MIT
author:              "Fernando Silva"
maintainer:          "fernandonsilva16@gmail.com"
copyright:           "2021 Fernando Silva"
description:         Please see the README on GitHub at <https://github.com/githubuser/exercism-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- hspec

library:
  source-dirs: src

executables:
  exercism-haskell-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  exercism-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - exercism-haskell
